clear;clc
close all

%cd('C:\Users\admin\Documents\MATLAB\VIP\scheduling')

A_Input_Data
B_Date_Setting
C_Optimization_Variable_Calculation
D_Scrap_Minimize_Optimization
E_Production_Line_Designation
F_Scheduling_Matrix

H_Production_Complete_Check
I_Production_Order_Optimization
J_Scrap_Calculation
K_Production_Able_Transform

M_Weekend_Application
N_Scheduling_Result

H_Production_Complete_Check

O_Result_to_Excel